### ISSUE TITLE
Feature: make slskd binary executable in releases

### ISSUE THREAD

**Issue by tandy-1000** [slskd/slskd#247] opened 2021-11-10 12:10 UTC
This is just a usability improvement, but before running an update I have to run `chmod +x` on the slskd binaries, this could be worked into releases.

**Comment by jpdillingham** [comment] 2021-11-10 13:30
Thanks, this was bothering me too but not enough for me to remember to create an issue for it.

**Comment by jpdillingham** [comment] 2021-11-10 14:08
Interestingly, this appears to be a bug with GitHub Actions.

The macOS distributable has the `x` flag when built natively, from the intermediary build from CI, and in the release
The Linux distributable has the `x` flag when built natively, but not from the intermediary build from CI nor in the release

I haven't tested either of the ARM builds yet but I'd expect them to behave the same way as linux-x64.

**Comment by jpdillingham** [comment] 2021-11-10 15:27
Tracked it down to the upload step: https://github.com/actions/upload-artifact#permission-loss

The fix is to `chmod +x` the binaries prior to zipping them for release, and that PR has been merged.  I'm still testing some changes to configuration from #245, when that is done I'll create a release and this should be fixed moving forward.

**Comment by tandy-1000** [comment] 2021-11-10 16:10
> I haven't tested either of the ARM builds yet but I'd expect them to behave the same way as linux-x64.

I'm using arm64 builds, so seems like the same 



> Tracked it down to the upload step: https://github.com/actions/upload-artifact#permission-loss
> 
> The fix is to `chmod +x` the binaries prior to zipping them for release, and that PR has been merged in #250. I'm still testing some changes to configuration from #245, when that is done I'll create a release and this should be fixed moving forward.

Nice job!

**Comment by jpdillingham** [comment] 2021-12-17 16:31
I confirmed that this is fixed on Linux and macOS.  I@tandy-1000 can you confirm for arm64?

**Comment by tandy-1000** [comment] 2021-12-18 14:09
> I confirmed that this is fixed on Linux and macOS. @tandy-1000 can you confirm for arm64?

Yep, all good, but I noticed I can't use -c to specify a config file anymore which is a shame :x

**Comment by jpdillingham** [comment] 2021-12-18 22:26
Thanks for confirming.

I deliberately removed the option to specify the path to the config file because of the need for remote config to write to it, but after thinking about it a bit I don't think it is as tricky as I was imagining it to be, so I'll add it back.

**Closed by jpdillingham** 2021-12-18 22:26 UTC
Labels: enhancement
