### ISSUE TITLE
Unusable performance, frequent disconnects, too many UI elements being displayed

### ISSUE THREAD

**Issue by manuel-rw** [slskd/slskd#1036] opened 2024-01-01 22:32 UTC
Hi, thanks for making this project.
The current implementation works well for very small amounts of files, but when I open shares with > 100 files, the browser starts to hang up to 30 seconds.
This makes the page unusable. Sometimes, clicks don't even register at all.
This is due to thousands of file HTML elements being rendered  which crushes RAM & performance.
Why is there is "collapsed by default" or limit / pagination?

Sometimes, the page goes fully blank and shows this after one minute:
![image](https://github.com/slskd/slskd/assets/30572287/16a483c0-3245-4986-a7b4-6ac60ac122f7)

I'm unable to open developer tools to investigate why rendering takes this long - but the amount of elements makes it pretty clear that this is most likely the cause.
As an example: Slskd is unusable with a share of ``321633`` files and ``31564`` directories.
Although this issue applies to both search and browse, browse is much worse and there is no "fold" toggle.

**Comment by jpdillingham** [comment] 2024-01-02 19:38
Thanks for reporting this, closing as duplicate of #317

**Closed by jpdillingham** 2024-01-02 19:38 UTC
Labels: duplicate
