### ISSUE TITLE
Provide a way to stop a search from the UI

### ISSUE THREAD

**Issue by mmnaseri** [slskd/slskd#242] opened 2021-11-09 02:51 UTC
It would be great if we could stop a search mid-way from the UI.

**Comment by jpdillingham** [comment] 2021-11-09 13:07
Thanks for raising this!  This is a duplicate of #198, which is currently at the top of the `Next Up` column on the [Project Board](https://github.com/slskd/slskd/projects/1).

**Closed by jpdillingham** 2021-11-09 13:07 UTC
Labels: duplicate
