### ISSUE TITLE
Auto-join rooms on slskd startup

### ISSUE THREAD

**Issue by Yousef40x** [slskd/slskd#1008] opened 2023-12-08 20:42 UTC
Auto-join rooms on slskd startup

_Originally posted by @Yousef40x in https://github.com/slskd/slskd/issues/999#issuecomment-1847817968_

**Comment by Yousef40x** [comment] 2023-12-08 20:45
Auto-join rooms on slskd startup

**Comment by jpdillingham** [comment] 2023-12-09 18:08
Duplicate of #999

**Closed by jpdillingham** 2023-12-09 18:08 UTC
