### ISSUE TITLE
Ensure usernames and passwords containing underscores and other characters can authenticate as expected

### ISSUE THREAD

**Issue by toketin** [slskd/slskd#1040] opened 2024-01-07 16:32 UTC
Hi, I'm trying to setup slskd dockerized, but I'm not able to connect to soulseek. I've tried to add the slskd username and password both like environment field on the docker compose, and also directly on the yaml file.

In any case I'm still getting this error: `Disconnected from the Soulseek server: invalid username or password`.

What should I do? 

Thanks in advance!

**Comment by jpdillingham** [comment] 2024-01-07 16:54
That's a fairly straightforward issue; you're connecting to the server properly and you have values for username and password set, but you're supplying the wrong password for the user.  It could be that you have a typo, or there might be an issue with your config that is passing a username/password that's different from what you intended.

Turning on [debugging](https://github.com/slskd/slskd/blob/master/docs/config.md#development-flags) will cause the application to dump the config to console at startup; you can use this to see what the username and password is and where the values are coming from.

**Comment by toketin** [comment] 2024-01-07 17:04
I've enabled the debug, username and password are passed correctly:

```
    password=my_pass (EnvironmentVariableConfigurationProvider)
    port=2271 (DefaultValueConfigurationProvider)
    username=my_username (EnvironmentVariableConfigurationProvider)
```

**Comment by jpdillingham** [comment] 2024-01-07 17:08
Have you confirmed that you can log in successfully using those credentials in another client?

**Comment by toketin** [comment] 2024-01-07 17:15
Yes using Nicotine+ and setting the same soulseek server vps.slsknet.org:2271, username and password, I can connect without problem.

**Comment by jpdillingham** [comment] 2024-01-07 17:34
Does either your username or password contain any special characters?  For example, anything from the unicode codepage, accents, kanji, etc

**Comment by oleksiiha** [comment] 2024-01-07 18:06
Hi, @jpdillingham, I also having same issue, first time user. I indeed have `#` in my password, hope that helps.

**Comment by toketin** [comment] 2024-01-07 18:17
I've just `_` on my password. On the enviroment variables I can use `SLSKD_SLSK_PASSWORD` without ""? I mean `SLSKD_SLSK_PASSWORD=password` is right?

**Comment by jpdillingham** [comment] 2024-01-07 18:22
As long as the debug output at the start of the application shows the correct username and password, the configuration should be correct.

To be clear, the message:

> Not connecting to the Soulseek server; username and/or password invalid. Specify valid credentials and manually connect, or update config and restart.

Indicates a configuration problem.

The messages:

> Disconnected from the Soulseek server: invalid username or password
> An unhandled exception has occurred while executing the request.: Soulseek.LoginRejectedException: The server rejected login attempt: INVALIDPASS

Indicate an issue with the username or password.  If the debug view is showing the correct username and password, and those same values work to connect in a different client, it's probably an issue with slskd, but I'm having a hard time imagining how.

**Comment by toketin** [comment] 2024-01-07 18:51
Ok I've been able to connect!

On my password I've deleted the underscore and used just letters.

**Comment by jpdillingham** [comment] 2024-01-07 20:55
Thanks for following up @toketin.  I'm reopening this so I'll remember to investigate the special characters.

@oleksiiha are you still having issues?

**Comment by oleksiiha** [comment] 2024-01-07 21:04
Thanks @jpdillingham, problem was on my side, though very similar symptoms. Not anymore.

**Comment by jpdillingham** [comment] 2024-01-28 23:54
I tried a password containing underscores and some special characters and it worked with both the YAML config and environment variables.

I did find that I had to remember to escape some characters (like `$` needed to be `\$`) or they'd come through as ASCII numbers instead of characters.

I'll close this for now since I couldn't reproduce, but if anyone else has issues I'll reopen.

**Closed by jpdillingham** 2024-01-28 23:54 UTC
Labels: question

**Comment by janaxhell** [comment] 2024-12-29 19:27
Hi, I was smashing my head on this in the past few days, because I have a perfectly working nicotine+ instance, but with the same username containing a "_" I couldn't connect wit slskd. I have now succeeded in doing so by replacing vps.slsknet.org 2271 with server.slsknet.org 2242 in the soulseek: section of slskd.yml. As I restarted the container with that setting, it became immediately green.
