### ISSUE TITLE
Logs filling with "SQLite Error 1: 'no such table: filenames'"

### ISSUE THREAD

**Issue by moondownr** [slskd/slskd#683] opened 2022-10-09 17:29 UTC
While routinely defragging my btrfs filesystem (yes it's me again) my script found a lot of fragmentation in some slskd log files.
"Hm, this never happened before", thought I, and decided to investigate.

And here's what I found:

![Screenshot from 2022-10-09 20-18-58](https://user-images.githubusercontent.com/23419209/194770850-8a9bab08-6ac0-4feb-8403-74902103868a.png)

Bewildered, I downloaded the 649 Mb log file and looked inside:

![Screenshot from 2022-10-09 20-24-27](https://user-images.githubusercontent.com/23419209/194770857-288c0921-87c3-4cef-bbc8-e17f7bd561af.png)

Entire slskd logs folder was >2GB. I can't remember changing anything drastic recently, except for updating slskd a few weeks ago.

**Comment by jpdillingham** [comment] 2022-10-09 19:29
That's odd, I have some logic that is specifically designed to prevent this.

The solution is to delete `/data/shares.db` and `/data/shares.db.bak` and restart, which should cause your shares to be re-scanned.

I'll have to see why this isn't working as intended.  Thanks for raising this.

**Comment by jpdillingham** [comment] 2022-10-09 23:15
#686 adds more granular schema checks which might help with this.  The existing code explicitly checks whether the `filenames` table exists while validating, but since that table is backed by the `fts5` extension there's several other related tables that might be missing in this case.

I tried manually deleting this table and running the application, and it detected the missing table and forced a scan, as expected, so I'm not sure how this is happening.

**Comment by moondownr** [comment] 2022-10-09 23:34
I did have an issue with shares database being stored in a db on disk https://github.com/slskd/slskd/issues/651. Right now I have "storage_mode=memory" in settings.

**Comment by jpdillingham** [comment] 2022-10-15 14:51
I was able to reproduce this (took me a minute to connect the dots) by forcibly clearing connection pools, which caused the in-memory database to be lost.  This is a side effect of using in-memory databases with SQLite; they disappear when the last connection disconnects.

I think connections to these are probably being pooled (even though it's not enabled explicitly) which is managing to keep them alive long enough for search results to start to come in.

To solve this I'll need to create a "keep-alive" connection and hold it open as long as the app is running.

**Comment by jpdillingham** [comment] 2022-10-15 14:53
I also need to forcibly quit the application if this specific error is encountered while servicing a search request; the application won't recover on its own.

**Comment by moondownr** [comment] 2022-10-16 02:03
Happened again (starting on 15.10). Not sure what useful info I might add.

**Comment by jpdillingham** [comment] 2022-10-23 16:00
A fix was released in [0.16.27](https://github.com/slskd/slskd/releases/tag/0.16.27).  If I'm interpreting the SQLite documentation correctly, this should fix the problem for good by opening (and leaving open) a connection to the database after initialization.

I've added a check to make sure the table exists.  Should this check fail the application will crash deliberately.

**Comment by jpdillingham** [comment] 2023-06-25 22:42
Thanks for reporting this @divcyb! Bunch of questions:

* Does this continue if you restart the application?
* How long had the app been running before you started seeing this?
* What operating system are you using?
* What kind of hardware? Are you memory constrained (~4gb or less)?

To shed a little light on this; the `filenames` table is stored in memory only, and it's volatile, so it gets deleted when the last connection to it closes.  I had made a change that I believed would establish a connection at startup and keep it open indefinitely, but in your case, something caused it to close. 

I see an earlier comment of mine stating that the app needs to be restarted to fix this and off the top of my head I can't think of why that would be.  I'll investigate.

**Comment by jpdillingham** [comment] 2023-06-27 14:30
Thanks for following up! I captured this in #926

**Closed by jpdillingham** 2023-06-27 14:30 UTC
Labels: bug
