### ISSUE TITLE
Downloads get stuck, can't cancel on some systems (version 0.16.9 and newer; if you're affected, use 0.16.8 until this issue is resolved)

### ISSUE THREAD

**Issue by Moondownr** [slskd/slskd#598] opened 2022-08-17 21:07 UTC
Upgraded for the first time in 3 or 4 months today, skipping many versions.
Downloads get stuck near completion (I have two right at 92 and 96 percent. out of 14 downloads total since the upgrade). Other files start and finish downloading, and the stuck ones never resume. Trying to cancel does not remove the downloads from the list. Corresponding files are absent in both the "incomplete" and "complete" folders.

**Comment by Moondownr** [comment] 2022-08-17 21:09
Same thing seems to happen with uploads - I have a number of "blue" uploads stuck at 100%, and a couple stuck below 100%.

**Comment by Moondownr** [comment] 2022-08-17 21:12
A shot in the dark, but might be connected to the apparent inclusion of the "round robin" feature.

**Comment by jpdillingham** [comment] 2022-08-17 21:40
Thanks for reporting this.  In your app directory you should have a `transfers.db` file in `/data`, could you please email that to logs@slskd.org?

**Comment by Moondownr** [comment] 2022-08-17 21:54
I got frustrated and restored 0.16.4 from backup (which fixed the issue).
Transfers.db was not overwritten, but I'm not sure how useful it will be now. For what it's worth, sent it anyway.
Sorry about that. If you have trouble reproducing, I'll redo update tomorrow or in a few days.

**Comment by jpdillingham** [comment] 2022-08-17 22:55
Thanks for sending the database file.  It all looks good, but there's logic in the application to clean up "dangling" transfer records at startup so I think the problem may be obscured by that.

I'm going to be releasing the changes in #599 shortly; I have a hunch that these problems might have been caused by out-of-order updates to the database, causing things to appear to be stuck.

I don't have an answer for why files weren't present in either of the output directories; there's no code that cleans up partial files after a failed transfer.

**Comment by jpdillingham** [comment] 2022-08-17 22:58
[0.16.11](https://github.com/slskd/slskd/releases/tag/0.16.11) should be released about 30 minutes from when this post was made.

If you wouldn't mind, please give it a shot and let me know if the problems persist.  If they do, please stop the application and grab `transfers.db` without restarting first, this should give me an accurate picture of what's going on (with the records anyway).

**Comment by jpdillingham** [comment] 2022-08-17 22:59
Also, can you provide details about your hosting environment? OS, hardware, that sort of thing.  I'm curious whether this may be an issue specific to low-spec hardware.

**Comment by Moondownr** [comment] 2022-08-19 01:34
Upgraded to 0.16.12, seeing the same behaviour. Additional observation: progress bars for downloads jumping back and forward again multiple times (46% - 42% - 57% - 70% - 58%...), including jumping all the way to 100% (at which point the next download begins) and then back to 94% and getting stuck there.

Sending transfers.db now.

**Comment by Moondownr** [comment] 2022-08-19 01:36
System:    Host: minimoon Kernel: 5.4.0-124-generic x86_64 bits: 64 Console: tty 1 Distro: Ubuntu 20.04.4 LTS (Focal Fossa) 
Machine:   Type: Laptop System: Apple product: Macmini3,1 v: 1.0 serial: <superuser/root required> 
           Mobo: Apple model: Mac-F22C86C8 serial: <superuser/root required> UEFI: Apple v: MM31.88Z.0081.B06.0904271717 
           date: 04/27/09 
CPU:       Dual Core: Intel Core2 Duo P7350 type: MCP speed: 1593 MHz min/max: 1596/1995 MHz 
Graphics:  Device-1: NVIDIA C79 [GeForce 9400] driver: nvidia v: 340.108 
           Display: server: X.org 1.20.13 driver: nvidia tty: 213x34 
           Message: Unable to show advanced data. Required tool glxinfo missing. 
Network:   Device-1: NVIDIA MCP79 Ethernet driver: forcedeth 
           Device-2: Broadcom and subsidiaries BCM4321 802.11a/b/g/n driver: b43-pci-bridge 
Drives:    Local Storage: total: 7.28 TiB used: 3.64 TiB (50.0%) 
Info:      Processes: 257 Uptime: 58m Memory: 3.59 GiB used: 1.72 GiB (47.9%) Init: systemd runlevel: 5 Shell: fish 
           inxi: 3.0.38

**Comment by jpdillingham** [comment] 2022-08-19 02:28
Thanks for sending the updated database.  This seems to confirm my suspicion that updates are being processed out of order, but I have no idea how it might be happening.  I've been running Prime95 to load my system while downloading a bunch of files and can't replicate the problem, even when my CPU and RAM are at 99% and my mouse cursor is skipping around.

Are you running the slskd executable? or the Docker container?

Also, there should be logs in `/app/logs`, could you zip and email those as well? That should confirm whether events are being sent out of order.

**Comment by jpdillingham** [comment] 2022-08-19 03:51
0.16.13 is building now and should be ready in about 30 minutes.

I've added verbose logging of the database updates for transfer records in an attempt to prove or disprove the out-of-order theory, if you would please set the new `experimental` option to `true`; this will cause a bunch of warnings to be logged while transfers are in progress, like:

```
[22:42:07 WRN] => [0bef509e-0ba8-4fe3-aa3e-fbe279f886b4] 215 - Microphone Fiend.mp3 | InProgress | 4.48650973284264
[22:42:07 WRN] <= [0bef509e-0ba8-4fe3-aa3e-fbe279f886b4] DONE
[22:42:07 WRN] => [0b25407a-5389-4f52-84f4-73fa708c8a34] 215 - Microphone Fiend.mp3 | InProgress | 7.178415572548223
[22:42:07 WRN] <= [0b25407a-5389-4f52-84f4-73fa708c8a34] DONE
[22:42:07 WRN] => [04b9498c-938c-491b-993d-baefabd7c8b5] 215 - Microphone Fiend.mp3 | InProgress | 10.767623358822336
[22:42:07 WRN] <= [04b9498c-938c-491b-993d-baefabd7c8b5] DONE
[22:42:07 WRN] => [8f8ac71a-f262-48d8-af3e-32916092eb06] 215 - Microphone Fiend.mp3 | InProgress | 14.356831145096447
[22:42:07 WRN] <= [8f8ac71a-f262-48d8-af3e-32916092eb06] DONE
[22:42:08 WRN] => [c056a81b-cf17-4b76-9f76-53ec913ba1d3] 215 - Microphone Fiend.mp3 | InProgress | 17.94603893137056
[22:42:08 WRN] <= [c056a81b-cf17-4b76-9f76-53ec913ba1d3] DONE
```

This will tell me if anything backtracks or lingers beyond the lifetime of the transfer.

I also refactored the code I'm using to rate limit updates; there's a small chance that was the cause of this so it might be fixed.

**Comment by jpdillingham** [comment] 2022-08-19 03:54
If you'd prefer to search the logs yourself, you're looking for any set of `=>` and `<=` that don't have a matching value; this indicates that another thread is executing an update at the same time and that there's a race condition that would cause this issue.  You're also looking for the very last entry for a given file, it should report `Completed, Succeeded | 100`.

**Comment by Moondownr** [comment] 2022-08-19 10:39
I'm running the executable. CPU and RAM usage is low. This is my file server, it doesn't do much. Slskd uses ~20% of CPU when scanning shares, negligible amount later, RAM almost never reaches 60%. There is however a significant amount of iowait generated by slskd in addition to running backups and btrfs background tasks (5400 rpm hard drives). Scanning shares also takes a while.


I upgraded to 0.16.13 and enabled the experimental option. Here is the section of the logs pertaining to the file "11 - Waving a White Flag.flac" that appears stuck on 86% after jumping back and forth.

> [13:26:42 WRN] => ["a6914073-7dc7-4571-a052-3263ceace3c6"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "Initializing" | 0
> [13:26:43 WRN] <= ["a6914073-7dc7-4571-a052-3263ceace3c6"] DONE
> [13:26:43 INF] [DOWNLOAD] [bcastle21/@@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac] Queued, Remotely => Initializing
> [13:26:43 WRN] <= ["c56f9aae-5cd7-40d1-9c26-c420f25365e1"] DONE
> [13:26:43 WRN] => ["cc032217-f608-4765-bb11-fc02dcfc283f"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 0
> [13:26:43 WRN] <= ["cc032217-f608-4765-bb11-fc02dcfc283f"] DONE
> [13:26:43 INF] [DOWNLOAD] [bcastle21/@@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac] Initializing => InProgress
> [13:26:43 WRN] => ["1e953456-d0ba-46ad-b1ac-fd1c183340d5"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 0
> [13:26:43 WRN] <= ["1e953456-d0ba-46ad-b1ac-fd1c183340d5"] DONE
> [13:26:43 WRN] => ["4558280c-107f-46a4-b0d1-869397e62a98"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 0.0667762140911831
> [13:26:43 WRN] <= ["4558280c-107f-46a4-b0d1-869397e62a98"] DONE
> [13:26:43 WRN] => ["0a56fd6b-3398-4fee-a3bb-976aaf83029a"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 0.20032864227354932
> [13:26:44 WRN] <= ["0a56fd6b-3398-4fee-a3bb-976aaf83029a"] DONE
> [13:26:44 WRN] => ["b9db7301-eda4-4799-9494-9330aa6b581b"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 0.6143411696388845
> [13:26:44 WRN] <= ["b9db7301-eda4-4799-9494-9330aa6b581b"] DONE
> [13:26:44 WRN] => ["bf1e639c-37a4-4965-aaf5-1bd142607a51"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 1.2420375820960057
> [13:26:44 WRN] => ["6dfa8610-521c-44db-994c-07638862b730"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 2.5508513782831943
> [13:26:44 WRN] <= ["bf1e639c-37a4-4965-aaf5-1bd142607a51"] DONE
> [13:26:45 WRN] => ["2e255acf-fb37-4a89-a27a-3ee47172b3c2"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 13.562249081919289
> [13:26:45 WRN] <= ["6dfa8610-521c-44db-994c-07638862b730"] DONE
> [13:26:46 WRN] => ["212247ee-fdf4-44cf-9412-5aac7d025b2e"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 17.341782799480253
> [13:26:46 WRN] <= ["2e255acf-fb37-4a89-a27a-3ee47172b3c2"] DONE
> [13:26:46 WRN] => ["2e9507e6-c128-4beb-b993-b3aed8c58b56"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 23.157991046822303
> [13:26:47 WRN] <= ["212247ee-fdf4-44cf-9412-5aac7d025b2e"] DONE
> [13:26:47 WRN] => ["7cd6dd76-79a8-4310-a09f-11c9a790c8e0"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 36.55997721492275
> [13:26:47 WRN] => ["67395c30-3410-4f95-97d2-ed0f9916ab45"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 44.11904465004468
> [13:26:47 WRN] <= ["7cd6dd76-79a8-4310-a09f-11c9a790c8e0"] DONE
> [13:26:47 WRN] => ["75c1cf03-aecf-4f2c-9a76-2625c592d42e"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 45.80848286655161
> [13:26:48 WRN] <= ["75c1cf03-aecf-4f2c-9a76-2625c592d42e"] DONE
> [13:26:48 WRN] => ["6524e74f-2c9d-444b-b129-c842b7c402f9"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 49.64811517679464
> [13:26:48 WRN] <= ["2e9507e6-c128-4beb-b993-b3aed8c58b56"] DONE
> [13:26:48 WRN] => ["9c0a93ab-83c0-4cc8-a45c-8e567eb479ec"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 55.24396191763579
> [13:26:48 WRN] <= ["6524e74f-2c9d-444b-b129-c842b7c402f9"] DONE
> [13:26:48 WRN] => ["5fb2d4b9-9b0d-42e0-b95a-6617cdf0895f"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 73.13998729407285
> [13:26:48 WRN] <= ["5fb2d4b9-9b0d-42e0-b95a-6617cdf0895f"] DONE
> [13:26:48 WRN] => ["b4c0043a-a1d8-44c1-85a0-7a2f72fa4787"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 74.26850531221385
> [13:26:49 WRN] <= ["b4c0043a-a1d8-44c1-85a0-7a2f72fa4787"] DONE
> [13:26:49 WRN] => ["3e77263c-704b-40cc-99bc-615c114f298e"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 81.30004065601543
> [13:26:49 WRN] <= ["3e77263c-704b-40cc-99bc-615c114f298e"] DONE
> [13:26:49 WRN] => ["9e6dc96e-5ce7-437a-aec7-0f77925503f3"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 86.38838816976359
> [13:26:49 WRN] <= ["9c0a93ab-83c0-4cc8-a45c-8e567eb479ec"] DONE
> [13:26:49 WRN] <= ["67395c30-3410-4f95-97d2-ed0f9916ab45"] DONE
> [13:26:49 WRN] => ["557c2586-995a-48e5-baa4-1c56135e695a"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "InProgress" | 94.17449473279554
> [13:26:49 WRN] <= ["557c2586-995a-48e5-baa4-1c56135e695a"] DONE
> [13:26:49 WRN] => ["71e504f9-33a5-4ce4-9ec1-7cab8765c153"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "Completed, Succeeded" | 100
> [13:26:49 WRN] <= ["71e504f9-33a5-4ce4-9ec1-7cab8765c153"] DONE
> [13:26:49 INF] [DOWNLOAD] [bcastle21/@@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac] InProgress => Completed, Succeeded (21684368/21684368 = 100%) @ 3.2 MB/s
> [13:26:49 WRN] => ["c49291a3-ae21-4d7b-ba23-410404e61e2e"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "Completed, Succeeded" | 100
> [13:26:49 WRN] <= ["c49291a3-ae21-4d7b-ba23-410404e61e2e"] DONE
> [13:26:49 WRN] => ["ffb15438-5624-4b30-8e5f-175e5eaca318"] @@lrfkq\Soulseek Downloads\complete\The Smile - A Light For Attracting Attention (2022) [FLAC]\11 - Waving a White Flag.flac | "Completed, Succeeded" | 100
> [13:26:49 WRN] <= ["ffb15438-5624-4b30-8e5f-175e5eaca318"] DONE


Here I don't see evidence of backwards progress, however it was evident while watching the progress bar. There is however a repeating "Completed, Succeeded" message. I will send the logs shortly.

**Comment by Moondownr** [comment] 2022-08-19 10:47
I am rolling back to 0.16.4 for now.

**Comment by Moondownr** [comment] 2022-08-19 10:58
No weird behaviour on 0.16.4 whatsoever (no surprise, I've been using it for several month without issue).

**Comment by Moondownr** [comment] 2022-08-19 11:03
Weird, this time the "stuck" files seemed to actually be in the downloads folder, despite appearing blue and unremovable in the interface.

**Comment by jpdillingham** [comment] 2022-08-19 12:43
Thank you _very much_ for sending logs over again, this has made it very easy to identify the issue.  

I have found the smoking gun, and while the symptom is what I expected (updates executed out of order) the actual cause is much worse.

In the first example I picked out, I see the following:

```
[13:25:37 WRN] => ["6a49ffad-b2c8-41dc-8d2f-4f4f4bd304ce"] <filename> | "InProgress" | 0.17432078298603476
[13:25:38 WRN] => ["414e9f4a-9062-4151-bbdb-2fc6977a9f3b"] <filename> | "InProgress" | 0.6159334332173227
[13:25:38 WRN] <= ["414e9f4a-9062-4151-bbdb-2fc6977a9f3b"] DONE
[13:25:41 WRN] <= ["6a49ffad-b2c8-41dc-8d2f-4f4f4bd304ce"] DONE
```

What's happening here is that the progress update of 0.17 is initiated, and 1 second later, an update to 0.61 is as well.  The 0.61 update executes immediately, while the 0.17 update doesn't update until _four seconds_ after it was initiated.

I'm absolutely baffled by this behavior, but regardless of the cause it means I need to rethink how I'm handling updates.

Storage of transfer data in SQLite was introduced in #569 and released in [0.16.9](https://github.com/slskd/slskd/releases/tag/0.16.9), so 0.16.8 is the newest version without this issue.

**Comment by Moondownr** [comment] 2022-08-19 13:42
No, same problem after chattr +C. However, files **do** finish downloading, it's only in UI that the progress stops. I don't know why on the first occasion files weren't there, maybe due to me trying to cancel the transfer multiple times.

**Comment by jpdillingham** [comment] 2022-08-19 14:56
[0.16.4](https://github.com/slskd/slskd/releases/tag/0.16.14) is building now and should be ready in 30 minutes.

In #604 I added an explicit check of the THREADSAFE flag used to compile the included SQLite binaries, to rule out the possibility that non-thread-safe binaries are being baked into the build somehow (probably not, but SQLite binaries are weird and make me nervous)

I also added an explicit set of the threading mode which defaults to `MULTITHREADED`.  The defaults here should be THREADSAFE=1 and a threading mode of `SERIALIZED`.  I merged a PR yesterday to set this to `MULTITHREADED` and it doesn't seem to have improved anything.

I have a hunch that what is happening here is that I'm just using SQLite wrong; putting too much trust in Entity Framework to "do the right thing" with respect to pooled connections and concurrency, which is opening the door to out-of-order updates.

For whatever reason, something on your system, and it very well could be btrfs, is randomly causing updates to lag by several seconds, which opens the door for other threads to complete while those are hanging.

I've added the ability to set the threading mode via the new `SQLiteThreadingMode` flag, but the more I think about it the more I doubt it will do anything with the application as it is right now.

This evening I will make a change that will limit the number of connections to `transfers.db` to 1, getting rid of `DbContextFactory` and connection pooling, and with that in place I'm expecting that setting `SQLiteThreadingMode` to `SERIALIZED` will fix your issue (as it forces updates through a mutex), but will _probably_ introduce random hangups which are already happening but are constrained to a single thread.

**Comment by Moondownr** [comment] 2022-08-19 21:03
I see that the default value of "sqLiteThreadingMode" in the latest version is "3". Should I set it to "SERIALIZED"?

**Comment by jpdillingham** [comment] 2022-08-19 21:28
You can give it a shot but it probably won't have any effect until the next update.

**Comment by Moondownr** [comment] 2022-08-19 21:36
> Property 'SQLiteThreadingMode' not found on type 'slskd.Options'.

> Property 'sqLiteThreadingMode' not found on type 'slskd.Options'.

**Comment by jpdillingham** [comment] 2022-08-19 22:08
Sorry, it's `flags.sqlite_threading_mode` in the yaml.  Alternatively `--sqlite-threading-mode` via CLI or `SQLITE_THREADING_MODE` via envar.

**Comment by Moondownr** [comment] 2022-08-19 22:31
[System.InvalidOperationException: Invalid SQLite threading mode 1; select either MULTITHREADED (2) or SERIALIZED (3)](url)

"3" means SERIALIZED already. And you were right, doesn't make a difference yet.

**Comment by jpdillingham** [comment] 2022-08-19 22:51
> "3" means SERIALIZED already. And you were right, doesn't make a difference yet.

Yeah I had that backwards for a bit.  Serialized should be the default out of the box, and I think setting it to `MULTITHREADED` will likely introduce more problems, now that I've done some more research.  I'll probably remove that flag once this is resolved.

[0.16.16](https://github.com/slskd/slskd/releases/tag/0.16.16) is on its way out.  This update removes all asynchronous database logic for transfers.  I have high hopes for this one 🤞 

If this doesn't work it means that I'll need to create a queue to push transfer state and progress updates into, and then create something that reads from that queue synchronously and on a single thread.  If it comes to this I will be baffled, as this is what `SERIALIZED` is supposed to do.

It's also possible that the issue is Entity Framework internals and I may consider ripping that out in favor of Dapper which is probably a better fit anyway.

**Comment by Moondownr** [comment] 2022-08-19 23:20
![image](https://user-images.githubusercontent.com/23419209/185718634-c24cc5da-3db3-408f-81ce-958bb353b38b.png)
:(

**Comment by jpdillingham** [comment] 2022-08-20 03:29
I've finally been able to reproduce this by putting the application directory on a network share and running it over wifi while also transferring a large file from my fileserver.

What I'm learning is that I don't really know much about Entity Framework (the ORM I'm using) and that I haven't carefully thought through the use case here.

I'm adding application level locking to prevent this from happening.

**Comment by jpdillingham** [comment] 2022-08-20 04:48
#606 should fix this for good, but it will probably slow transfers down on your system because updates to the database are now blocking (as they should have been, but weren't).

I'm going to add an option to decrease the frequency of updates which should help, but long term I suggest adding some additional SSD storage to your server and putting the slskd application directory on it to help mitigate this.

**Closed** 2022-08-20 04:49 UTC
Labels: bug

**Comment by Moondownr** [comment] 2022-08-20 12:35
Thanks a lot, this has fixed the issue. Not noticing much of a speed difference: in not-so-frequent cases where I can get my full 100mbit down from the seeder, I still get ~100mbit, as always.

Yeah, this is a headless cupboard-dwelling early 2009 Mac mini with optical drive pulled out in favour of a second 2TB laptop HDD. I highly doubt I'll be replacing them with 2TB SSDs, considering it's SATAII. However, the whole btrfs experiment has been less than successful on the whole. I really wish I had gone with ext4, but I'm too lazy to nuke everything.

**Comment by jpdillingham** [comment] 2022-08-20 23:50
Glad to hear it worked! Thanks so much for hanging in there with me; if you hadn't this probably would have lingered for a long time.
