### ISSUE TITLE
Port forwarding with VPN passthrough (specifically Mullvad and qbittorrent-vpn)

### ISSUE THREAD

**Issue by tylernguyen** [slskd/slskd#365] opened 2022-02-21 15:20 UTC
Context:
- Unraid 6.10
- Want to pass `slskd` through another VPN wrapped container `hotio/qbittorrent-vpn`
- VPN Provider, Mullvad (which is fairly popular) does not allow for manual port forward selection, but instead generates a random port to be forwarded upon request.

Hence, once the `slskd` container traffic is passed by `--net=container:qbittorrent-vpn`, port `50000` still remains even if the listening port is changed within `slskd.yml`

![image](https://user-images.githubusercontent.com/3349081/154981086-6162108b-7700-450e-a52c-8e982fd0aa94.png)

As a result, while the soulseek web interface works and search/download functions normally. I cannot share/upload or find myself in the users tab.

It would be great if there is a way to expose the port specifically for port forwarding with strict VPN providers like Mullvad.

**Comment by jpdillingham** [comment] 2022-02-21 19:12
You should be able to set the port in `slskd.yml` or pass it as `SLSKD_SLSK_LISTEN_PORT`, then change the port mapping through docker accordingly, e.g:

```
docker run -d \
  -p 5000:5000 \
  -p 5001:5001 \
  -p 51234:51234 \
  -v /var/data/slskd:/app \
  -v /var/data/slskd/shared:/shared \
  -e "SLSKD_SLSK_LISTEN_PORT=51234" \
  --name slskd \
  --restart always \
  slskd/slskd:canary
```

When you look at the settings within the system tab of the UI, the listen port should be 51234.  If not, update `slskd.yml` (or delete the row specifying the listen port).  

I tested on my home network and was able to directly connect:

```
[Soulseek] [Soulseek.Network.PeerConnectionManager] [13:08:32 DBG] Attempting direct message connection to <redacted> (<redacted>:51234)
[Soulseek] [Soulseek.Network.PeerConnectionManager] [13:08:32 DBG] Direct message connection to <redacted> (<redacted>:51234) established. (type: Outbound, Direct, id: 0353777b-3539-4415-878c-c7602b588906)
```

**Comment by tylernguyen** [comment] 2022-02-22 03:58
@jpdillingham 

I've tried changing it via `slskd.yml` and/or `SLSKD_SLSK_LISTEN_PORT`, see:

![image](https://user-images.githubusercontent.com/3349081/155060457-fde0d583-69cd-46a7-8ae7-7d2bb4a9e472.png)

![image](https://user-images.githubusercontent.com/3349081/155060279-7bf880de-5137-476d-b09a-a3e3d879d9ba.png)

`56476` being the port forward given to me by Mullvad.

The same problem persists, however:

![image](https://user-images.githubusercontent.com/3349081/155060360-f012b33f-7afc-4ed5-ab73-1af222980172.png)

- It seems that 50000 is somehow still being forced when passing through another container's network and I'm unable to share as a result.

P.S. Here are the details for `qbittorent-vpn` for you to possible replicate this issue:

![image](https://user-images.githubusercontent.com/3349081/155060571-fc7eec80-c269-4097-bbe1-da9efc898ae5.png)

**Comment by jpdillingham** [comment] 2022-02-23 02:53
This looks like it might be an Unraid configuration issue.  Here's a thread on reddit from a user with a similar issue: https://www.reddit.com/r/unRAID/comments/b0jmzh/issues_with_docker_and_port_mapping/

The only thing that is actually hard coded about port 50000 is the `EXPOSE 50000`  instruction in the Dockerfile.  This is intended to be non-functional, however Unraid might have an issue with it.

Here's a screenshot of my Portainer configuration:

![image](https://user-images.githubusercontent.com/17145758/155253822-37951251-d851-41d5-9024-27a9ae9780f9.png)

You'll need to map port 56476 on your host to 56476 in the container, but your config screenshot shows that you're still mapping 50000 to 50000.

**Comment by jpdillingham** [comment] 2022-02-23 03:01
The PR merged above removes the `EXPOSE` instructions, so there's nothing left in the container that should be pinning the port to 50000.  The canary image should be available to pull about 30 minutes from this post.

**Comment by tylernguyen** [comment] 2022-02-24 01:34
So without the `EXPOSE` instructions, the container won't even work without VPN. Under a VPN environment, it still does not work.

So at the very least, I think you need to `EXPOSE` `5000` and `5001`.

I suspect that if you do `EXPOSE` `56476` as well, my problem will be resolved. Can we try that?

**Comment by jpdillingham** [comment] 2022-02-24 12:52
Sure, I'll push up a special tag this evening with that change.  The latest canary is working fine on portainer for me, so I think this is probably Unraid being picky about how ports are mapped with or without `EXPOSE`.  I think you should be able to resolve the issue by explicitly mapping the port, but I don't know enough about Unraid to say for certain.

**Comment by tylernguyen** [comment] 2022-02-24 12:57
It's definitely Unraid being picky about `EXPOSE`

I've tried explicitly mapping the port as well, that didn't do it for when the container is trafficking through another's network. Once you have the tag up, if it indeed fixes the problem, I can then raise the issue in the Unraid forum. If not the special tag doesn't fix it, we'll have to look elsewhere.

Thanks again for your time and help.

**Comment by jpdillingham** [comment] 2022-02-25 04:54
The image `slskd/slskd:0.14.4.65534-4b463b8` exposes 56476, give it a try!

**Comment by tylernguyen** [comment] 2022-02-25 06:09
Hm.. so it still doesn't work. Though I am now seeing/noticing an error:

`An unhandled exception has occurred while executing the request.`

This happens when searching for myself in the `Users` tab. Though I can see my files in `Browse`

I'm honestly at a lost for what could be wrong. Do you have any ideas of what I can try?

**Comment by jpdillingham** [comment] 2022-02-25 13:13
Unfortunately I'm at a loss, as I haven't used Unraid or a VPN container.  I'll add the 'help wanted' tag and hope that someone else can share their experience.

Regarding diagnostics, you can set the flags `SLSKD_DEBUG=true` and `SLSKD_SLSK_DIAG_LEVEL=Debug`.  This will give the most verbose log output.  It would be helpful if you could screenshot any errors you see, or if you wouldn't mind retrieving the log files from the container, you can email them to logs@slskd.org

**Comment by tylernguyen** [comment] 2022-02-25 14:06
I've just tried a containerized soulseek-qt docker trafficked through the same `qbittorent-vpn` and it's having the same issue as `slskd` so perhaps it's an Unraid/Mullvad related issue.

Additionally, it would be great to be able to set `UMASK` since all files downloaded are owned by root which makes moving things via SMB hard and troublesome (let me know if this warrants another issue made)

In any case, thank you for your help and work.

**Comment by jpdillingham** [comment] 2022-02-25 16:00
The file ownership issue has been discussed in #49; I think passing the desired user to docker is the prescribed solution for now, as there are some technical challenges with the other options.

Adding a VPN to the container was discussed in #222 and I agreed with the rationale that it would be better left up to other solutions.  Rereading that thread now, it looks like there are some alternative VPN containers you might try if qbittorrent-vpn isn't working.

I may still add Wireguard support if a passthrough configuration ends up being difficult.

**Comment by tylernguyen** [comment] 2022-02-25 18:08
Definitely +1 for built in vpn (wireguard) support.

I've tried other vpn containers but those also had the same issue.

**Comment by Davo1624** [comment] 2022-02-25 18:37
This is an issue for me as well. Trying to route slskd through qbittorrent-vpn (hotio image) I experience the same problems as @tylernguyen 

I am using docker-compose to generate my containers, host OS is unraid 6.9.2. I can route the realies/soulseek through qbit-vpn without issue.

Here is my compose:
```  slskd:
    container_name: slskd
    depends_on:
      - qbittorrent
    environment:
      - SLSKD_PUID=${PUID}
      - SLSKD_PGID=${PGID}
      - SLSKD_DOWNLOADS_DIR=/data/soulseek
      - SLSKD_INCOMPLETE_DIR=/data/soulseek/.incomplete
      - SLSKD_SHARED_DIR=/data/media/Music;/data/media/Music-unsorted
      - SLSKD_UPLOAD_SLOTS=3
      - SLSKD_SLSK_USERNAME=[redacted]
      - SLSKD_SLSK_PASSWORD=[redacted]
      - SLSKD_SLSK_LISTEN_PORT=58743
      - SLSKD_NO_AUTH=true
    image: slskd/slskd
    network_mode: service:qbittorrent
    restart: unless-stopped
    volumes:
      - ${CONF_PATH}/slskd:/app
      - ${DATA_PATH}:/data```
I can also verify that files downloaded by slsk are given root:root permissions, not the UID/GID permissions I specified in compose.

When trying to search for my username in slskd I get the following error:
```today at 1:30:46 PM[18:30:46 ERR] An unhandled exception has occurred while executing the request.
today at 1:30:46 PMSoulseek.SoulseekClientException: Failed to retrieve information for user [user]: Failed to establish a direct or indirect message connection to [user] ([vpn-ip]:58743)
today at 1:30:46 PM ---> Soulseek.ConnectionException: Failed to establish a direct or indirect message connection to [user]([vpn-ip]:58743)```

I also see this frequently in the logs:
```today at 1:31:09 PM[18:31:09 INF] Added child connection to [remote-user] ([remote-ip]:59472)
today at 1:31:09 PM[18:31:09 INF] Child connection to [remote-user] ([remote-ip]:59472) disconnected: Read error: Remote connection closed```

**Comment by jpdillingham** [comment] 2022-02-28 03:01
The variables `SLSKD_PUID/PGID` will have no effect, the container doesn't use these like he linuxserver.io images do.  To run the container as a specific user you'll want to use the `user` directive in your docker compose file.

`Failed to retrieve information for user [user]: Failed to establish a direct or indirect message connection to [user] ([vpn-ip]:58743)`

This error is expected if your port forwarding configuration isn't working.

`Child connection to [remote-user] ([remote-ip]:59472) disconnected: Read error: Remote connection closed`

This is normal, and I regret that it fills up the logs.  I'll create a new issue to move these to a different display or log them as debug messages.

**Comment by Davo1624** [comment] 2022-03-01 03:25
In the slskd documentation is says PUID and PGID are valid env vars. What purpose do they service if it's not for changing the owner of the files in `/data` container dir?

If I switch my image to realies/soulseek the network connects just fine and I can upload files to other users. It is connected through the qbit-vpn container with the same ports (58743)

![image](https://user-images.githubusercontent.com/85573606/156098619-805577bb-c1f9-41ee-8360-afd7462c9f7a.png)

This same port is port forwarded with my vpn provider as well. If there is something else I should be looking at as far as networking goes I am open to any suggestions :)

**Comment by jpdillingham** [comment] 2022-03-01 04:41
PUID and PGID were left over from a time before any thought was put into running as a different user; I've removed them now to avoid misleading anyone else.

Regarding your compose file, you will need to add:

```
    ports:
      - "58743:58743"
```

I'm thinking the `EXPOSE` command in the dockerfile might be causing some confusion here, for me as well. From what I read it seemed informational only but I'm wondering if compose and unraid are trying to be helpful and are adding implicit mappings.

I will play around and find out tomorrow; I'm creating an unraid VM at the moment.

**Comment by Davo1624** [comment] 2022-03-01 21:49
When I specify `network_mode: service:qbittorrent` in the compose for slskd there is no need to specify a port since qbittorrent and slskd are not communicating via the host port. I would assume the env var `SLSKD_SLSK_LISTEN_PORT=58743` would instruct the slskd container to listen on that port for connectivity and thus it is not necessary to specify it in the compose.

This is the same setup I use with the realies/soulseek container and it successfully connects to the soulseek network so I think you are correct regarding the EXPOSE command. If I can provide any additional info to help just let me know.

**Comment by jpdillingham** [comment] 2022-03-03 18:52
@Davo1624 I've removed the `EXPOSE` command entirely; please give the canary a try when it is out ~20 minutes after this post.

**Comment by Davo1624** [comment] 2022-03-03 20:58
I tried with the canary build but the same issue persists

Issue:
`[20:56:10 INF] Child connection to (user) (ip:port) disconnected: Read error: Remote connection closed`

Version:
```
version:
  current: 0.14.4.65534
  full: 0.14.4.65534 (0.14.4.65534-e99a175)
  isCanary: true
```

**Comment by tylernguyen** [comment] 2022-03-03 21:19
I don't think it's an `EXPOSE` issue. I've previously tried it without as well and it didn't work.

**Comment by jpdillingham** [comment] 2022-03-03 21:44
Taking a bit of a step back; child connections disconnecting aren't an indicator of port forwarding working or not working.  

To test whether port forwarding is working, either try to retrieve your user info ("Users" tab), or browse your own shares.  Alternatively you can enable logging at the debug level and watch for logs that mention incoming connections.

**Comment by Davo1624** [comment] 2022-03-03 21:46
Trying to retrieve my user info I get errors about not being able to connect:

` ---> Soulseek.ConnectionException: Failed to establish a direct or indirect message connection to davo1624 (ip:58743)`

**Comment by jpdillingham** [comment] 2022-03-03 21:50
Thanks for confirming.  Port forwarding definitely isn't working on your system, but I'm at a loss for what the issue is.  I'll update the title of this issue and hopefully someone with a working configuration can chime in.

**Comment by Eric-sson** [comment] 2022-03-04 09:43
I am also using Unraid and for me Port Forwarding doesn't work. 
Looking up my own username or share gives the below error.
---> Soulseek.ConnectionException: Failed to establish a direct or indirect message connection to ***** (*****:50000)

See below my docker compose with SLSKD_SLSK_LISTEN_PORT on standard 50000. Any idea?

version: "3"
services:
  slskd:
    container_name: slskd
    entrypoint:
      - ./slskd
    environment:
      - HOST_OS=Unraid
      - user=99
      - SLSKD_SLSK_PASSWORD=*****
      - SLSKD_DOWNLOADS_DIR=/data/usenet/music/complete
      - SLSKD_NO_AUTH=true
      - SLSKD_SHARED_DIR=/data/media/music
      - TZ=Europe/Paris
      - TCP_PORT_5001=5001
      - TCP_PORT_50000=50000
      - TCP_PORT_5000=5000
      - SLSKD_SLSK_USERNAME=*****
      - SLSKD_INCOMPLETE_DIR=/data/usenet/music/incomplete
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_BUNDLE_EXTRACT_BASE_DIR=/var/tmp/.net
      - SLSKD_HTTP_PORT=5000
      - SLSKD_HTTPS_PORT=5001
      - SLSKD_SLSK_LISTEN_PORT=50000
      - SLSKD_APP_DIR=/app
      - SLSKD_DOCKER_TAG=0.0.1
      - SLSKD_DOCKER_VERSION=0.14.4.0-a3328e8
      - SLSKD_DOCKER_REVISON=0
      - SLSKD_DOCKER_BUILD_DATE=
    expose:
      - 5000/tcp
      - 50000/tcp
      - 5001/tcp
    hostname: Tower
    image: slskd/slskd
    ipc: private
    labels:
      org.opencontainers.image.authors: slskd Team
      org.opencontainers.image.created: ""
      org.opencontainers.image.description: A modern client-server application for
        the Soulseek file sharing network
      org.opencontainers.image.documentation: https://github.com/slskd/slskd
      org.opencontainers.image.licenses: AGPL-3.0
      org.opencontainers.image.revision: 0
      org.opencontainers.image.source: https://github.com/slskd/slskd
      org.opencontainers.image.title: slskd
      org.opencontainers.image.url: https://slskd.org
      org.opencontainers.image.vendor: slskd Team
      org.opencontainers.image.version: 0.14.4.0-a3328e8
    logging:
      driver: json-file
      options:
        max-file: 1
        max-size: 50m
    networks:
      - host
    privileged: true
    security_opt:
      - label=disable
    volumes:
      - /mnt/user/appdata/slskd:/app:rw
      - /mnt/remotes/SYNOLOGY_data/:/data:rw
    working_dir: /slskd
networks:
  host:
    external: true

**Comment by tylernguyen** [comment] 2022-03-04 14:29
@Eric-sson 

Are you using a custom vpn network?  It doesn't like it in your config.

To be clear, `slskd` is working perfectly fine for me without custom network and vpn. It is only when routing through another container's vpn that it gives me problems. Hence, why I asked for the container to implement vpn support natively.

**Comment by Eric-sson** [comment] 2022-03-04 14:41
@tylernguyen 

No I am just using Host as Network Type. Would you mind posting your docker compose? Maybe I missed something..

**Comment by tylernguyen** [comment] 2022-03-04 14:43
I'm using Bridge. There's nothing special about the configuration. Did you port forward port `50000`? You can also tried port forwarding a custom port and setting it on the config.yml

**Comment by Eric-sson** [comment] 2022-03-04 15:15
Ok checked the portforwarding, removed it and applied it again. And now it is working :)

**Comment by Davo1624** [comment] 2022-05-09 21:28
An update on this, I have tried routing slskd through a wireguard tunnel on host server instead of through a vpn container and am still not connectable. Just wanted to rule out the vpn container being the issue

**Comment by tylernguyen** [comment] 2022-05-10 05:34
I can confirm @Davo1624's statement. Also tried Unraid's new Wireguard docker implementation and had the same issue as before.

@jpdillingham Would it be possible for VPN implementation in the slskd docker?

**Comment by jpdillingham** [comment] 2022-05-11 02:41
I was able to get this working with [gluetun](https://github.com/qdm12/gluetun)

```yml
version: "3"
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - "5000:5000"
      - "5001:5001"
      - "55279:55279"
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=<private key>
      - WIREGUARD_ADDRESSES=<ip range>
      - SERVER_CITIES=Amsterdam
      - FIREWALL_VPN_INPUT_PORTS=55279
  slskd:
    depends_on:
      - gluetun
    network_mode: "container:gluetun"
    image: slskd/slskd:latest
    container_name: slskd
    environment:
      - SLSKD_SLSK_LISTEN_PORT=55279
    volumes:
      - /var/slskd:/app
    restart: always
```

I found the [gluetun wiki](https://github.com/qdm12/gluetun/wiki/Mullvad) to be accurate.

**Comment by Davo1624** [comment] 2022-05-11 13:26
dunno what the issue could be then. I am routing my slskd traffic through a wireguard tunnel with torguard, port checker shows my vpn ip has port 50000 open, this is my compose:

`  slskd:
    container_name: slskd
    #depends_on:
      #- qbittorrent
    environment:
      - SLSKD_DOWNLOADS_DIR=/data/soulseek
      - SLSKD_INCOMPLETE_DIR=/data/soulseek/.incomplete
      - SLSKD_SHARED_DIR=/data/media/Music;/data/media/Music-unsorted
      - SLSKD_UPLOAD_SLOTS=3
      - SLSKD_SLSK_USERNAME=[user]
      - SLSKD_SLSK_PASSWORD=[pass]
      - SLSKD_SLSK_LISTEN_PORT=50000
      - SLSKD_HTTP_PORT=5000
      - SLSKD_NO_AUTH=true
      - SLSKD_REMOTE_CONFIGURATION=false
      - SLSKD_SLSK_NO_DNET=false
      - SLSKD_SLSK_DNET_NO_CHILDREN=false
      - SLSKD_SLSK_DNET_CHILDREN=25
    image: slskd/slskd:latest
    networks:
      - wg1
    ports:
      - 5000:5000
      - 50000:50000
    restart: unless-stopped
    user: ${PUID}:${PGID}
    volumes:
      - ${CONF_PATH}/slskd:/app
      - ${DATA_PATH}:/data`

wg1 being the local wireguard tunnel.

I can neither browse my own files or find my username in a search. When I connect to the same tunnel with the realies/soulseek container I do not have these issues.

**Comment by jpdillingham** [comment] 2022-05-11 15:42
@Davo1624 unfortunately this does mean that forwarding isn't working properly.  Your IP is reported as 146.70.34.xx and listen port is 52000; is this what you would expect?

Would you mind joining our [Discord](https://slskd.org/discord)? I'd like to have you try one last thing and I don't want to share any sensitive info here.

**Comment by tylernguyen** [comment] 2022-06-23 02:22
Just on update on this issue.

It seems that routing through Mullvad on Unraid works. It's just that you can't seem to browse your files or look your info up by yourself. Someone else needs to check if you are connectable.

@jpdillingham 

If there's a possible way to implement a self-check for VPN users, that would be great. Otherwise, feel free to close this issue and mark as partially resolved.

**Closed** 2024-02-06 07:21 UTC
Labels: help wanted, question
